Repository uwblueprint/shoe-project, pull requests merged in 2020-10, with the labels that each got.

#24 Adding react router to the project
  ui/package.json
  ui/src/App.tsx
  ui/src/index.tsx
  ui/src/pages/Home.tsx
  ui/src/pages/ShoeMap.tsx
  ui/src/pages/index.js
  ui/yarn.lock
Labels: frontend

#28 feat: Connect Postgres to backend
  cmd/server.go
  config/defaults.go
  config/getter.go
  go.mod
  go.sum
  internal/database/database.go
  restapi/api.go
  ui/src/App.tsx
Labels: backend

#31 Adding standardized styling files
  package-lock.json
  ui/src/pages/Home.tsx
  ui/src/pages/ShoeMap.tsx
  ui/src/styles/colors.js
  ui/src/styles/device.js
  ui/src/styles/index.js
  ui/src/styles/typography.js
Labels: frontend

#29 build: Add Docker compose
  .dockerignore
  Makefile
  README.md
  cmd/server.go
  docker-compose.yml
  docker/Dockerfile.dev
  docker/Dockerfile.prod
  go.sum
  ui/.prettierrc
  ui/package.json
  ui/src/index.tsx
Labels: infrastructure

#32 added prettier ignore and tslint
  ui/.prettierignore
  ui/package.json
  ui/yarn.lock
Labels: frontend

#48 Adding Github Actions workflow
  .github/workflows/go.yml
  .github/workflows/node.yml
  ui/src/styles/typography.js
Labels: infrastructure

#73 feat: Add design system colors and font
  ui/src/index.css
  ui/src/index.html
  ui/src/index.tsx
  ui/src/styles/colors.js
  ui/src/styles/colors.ts
  ui/src/styles/device.ts
  ui/src/styles/index.js
  ui/src/styles/index.ts
  ui/src/styles/typography.js
  ui/src/styles/typography.ts
Labels: frontend

#63 Add basic map to FE
  ui/package.json
  ui/src/pages/ShoeMap.tsx
  ui/yarn.lock
Labels: frontend
