Repository uwblueprint/shoe-project, pull requests merged in 2021-05, with the labels that each got.

#351 Making Seeding Quicker
  internal/database/migrations/migrations.go
Labels: backend

#353 Try/Catch Youtube URL Parsing
  ui/src/components/StoryDrawer.tsx
  ui/src/pages/Admin/Edit/UploadStory.tsx
Labels: frontend

#350 Bug fix: filter on map page only shows countries from visible stories
  go.mod
  go.sum
  restapi/authors.go
  restapi/endpoints_test.go
Labels: backend, bug

#346 Fix: Map Pin Placement
  ui/src/components/PinCluster.tsx
Labels: bug, frontend, map

#362 ToastyBoi 2.0
  ui/src/components/ToastyBoi.tsx
  ui/src/pages/Admin/AllStories/index.tsx
Labels: bug, priority: medium
