Repository uwblueprint/shoe-project, pull requests merged in 2021-03, with the labels that each got.

#234 Jeffrey/pin-preview
  ui/src/components/Pin.tsx
  ui/src/components/PinCluster.tsx
  ui/src/components/PinPreview.tsx
  ui/src/styles/typography.ts
Labels: frontend

#219 google oauth setup
  README.md
  cmd/seed.go
  config/getter.go
  go.mod
  go.sum
  internal/database/migrations/migrations.go
  internal/database/models/auth.go
  restapi/api.go
  restapi/auth.go
  restapi/endpoints_test.go
  restapi/redirects.go
  ui/src/hooks/auth.tsx
  ui/src/types/index.tsx
Labels: backend

#221 Pin placement
  cmd/seed.go
  cmd/server.go
  config/getter.go
  internal/location/coordinates.go
  internal/location/location.go
  internal/location/mapbox.go
  restapi/stories.go
  restapi/token.go
  testutils/location_finder.go
Labels: backend

#241 feat: Upload Story Page: Success, Loading, and Error States
  ui/src/pages/Upload.tsx
Labels: frontend

#239 Edit story backend
  internal/location/coordinates.go
  restapi/api.go
  restapi/endpoints_test.go
  restapi/stories.go
  ui/package.json
  ui/src/types/index.tsx
Labels: backend

#248 feat: All Stories Page: sorting, switches
  ui/.eslintrc.js
  ui/package.json
  ui/src/App.tsx
  ui/src/components/AllStoriesTabs.tsx
  ui/src/components/VirtualizedTable.tsx
  ui/src/components/index.ts
  ui/src/pages/AllStories.tsx
  ui/src/pages/index.ts
  ui/yarn.lock
Labels: frontend

#256 chore(deps): yarn-lock dependencies
  ui/package.json
  ui/yarn.lock
Labels: bug

#249 Delete Story By ID - Backend
  restapi/api.go
  restapi/endpoints_test.go
  restapi/stories.go
Labels: backend

#254 fix: make image optional in edit story
  restapi/stories.go
Labels: backend

#264 fix: All Stories table errors
  ui/package.json
  ui/src/pages/AllStories.tsx
  ui/yarn.lock
Labels: bug, frontend

#237 All stories backend
  restapi/endpoints_test.go
  restapi/stories.go
  testutils/database.go
Labels: backend

#263 feat: Countries - Backend
  internal/database/migrations/migrations.go
  internal/database/models/models.go
  restapi/api.go
  restapi/authors.go
  restapi/countries.go
Labels: backend

#257 Fixed Image deletion s3
  restapi/stories.go
Labels: backend

#272 Add cities data
  ui/src/data/cities.json
Labels: frontend

#255 View story
  ui/src/components/StoryDrawer.tsx
  ui/src/components/VirtualizedTable.tsx
  ui/src/pages/AllStories.tsx
  ui/src/pages/Upload.tsx
  ui/src/styles/typography.ts
Labels: frontend
