Repository uwblueprint/shoe-project, pull requests merged in 2021-04, with the labels that each got.

#274 Publish Stories - Backend
  restapi/api.go
  restapi/endpoints_test.go
  restapi/stories.go
Labels: backend

#266 Client Based Auth - Backend Modifications
  config/getter.go
  go.mod
  go.sum
  restapi/api.go
  restapi/auth.go
Labels: backend

#281 feat: add max file size limit on upload
  ui/src/pages/Upload.tsx
  ui/yarn.lock
Labels: frontend

#283 changed allstories to return visible and non-visible stories
  restapi/endpoints_test.go
  restapi/stories.go
  ui/src/pages/ShoeMap.tsx
Labels: backend, frontend

#267 feat: Visible Stories and Pending Changes Tables
  ui/package.json
  ui/src/__tests__/pages/AllStories.test.ts
  ui/src/components/StoryDrawer.tsx
  ui/src/components/VirtualizedTable.tsx
  ui/src/pages/AllStories.tsx
  ui/src/pages/AllStories/index.tsx
  ui/src/pages/AllStories/reducer.ts
  ui/src/pages/index.ts
  ui/src/styles/typography.ts
  ui/src/util/helpers.ts
  ui/yarn.lock
Labels: frontend

#288 fix: Pending table bug, general all stories component stylings
  ui/src/__tests__/pages/AllStories.test.ts
  ui/src/pages/AllStories/VisibilitySwitch.tsx
  ui/src/pages/AllStories/index.tsx
  ui/src/pages/AllStories/reducer.ts
  ui/src/styles/colors.ts
Labels: frontend

#282 feat: Search Stories Frontend
  ui/package.json
  ui/src/__tests__/pages/AllStories.test.ts
  ui/src/pages/AllStories/index.tsx
  ui/src/pages/AllStories/reducer.ts
  ui/yarn.lock
Labels: frontend

#280 feat: Add frontend auth
  ui/package.json
  ui/src/App.tsx
  ui/src/__tests__/hooks/auth.test.tsx
  ui/src/__tests__/pages/Admin/AllStories.test.ts
  ui/src/components/VirtualizedTable.tsx
  ui/src/hooks/auth.tsx
  ui/src/hooks/auth/index.tsx
  ui/src/hooks/auth/reducer.ts
  ui/src/pages/Admin.tsx
  ui/src/pages/Admin/AllStories/VisibilitySwitch.tsx
  ui/src/pages/Admin/AllStories/index.tsx
  ui/src/pages/Admin/AllStories/reducer.ts
  ui/src/pages/Admin/AllStories/types.ts
  ui/src/pages/Admin/Upload.tsx
  ui/src/pages/Admin/index.tsx
  ui/src/pages/Login.tsx
  ui/src/pages/ShoeMap.tsx
  ui/src/pages/index.ts
  ui/yarn.lock
Labels: frontend

#292 Generate Cookie when Domain is not HTTPS
  restapi/auth.go
Labels: backend

#295 Redirect HTTP to HTTPS
  server/server.go
Labels: backend

#298 feat: hifi login page, empty states, upload button
  ui/package.json
  ui/src/assets/images/shoeproject-logo.svg
  ui/src/assets/images/walking-people.svg
  ui/src/components/StoryDrawer.tsx
  ui/src/components/VirtualizedTable.tsx
  ui/src/pages/Admin/AllStories/index.tsx
  ui/src/pages/Admin/Upload.tsx
  ui/src/pages/Login.tsx
  ui/src/pages/ShoeMap.tsx
  ui/src/styles/colors.ts
  ui/src/styles/typography.ts
  ui/yarn.lock
Labels: design, frontend

#291 Feat: AllStories Filtering
  ui/src/__tests__/pages/Admin/AllStories.test.ts
  ui/src/components/VirtualizedTable.tsx
  ui/src/pages/Admin/AllStories/index.tsx
  ui/src/pages/Admin/AllStories/reducer.ts
  ui/src/pages/Admin/AllStories/types.ts
Labels: frontend

#300 Move Endpoints to Protected
  restapi/api.go
  restapi/auth.go
Labels: backend

#301 feat: show and hide stories when checked
  ui/src/pages/Admin/AllStories/index.tsx
  ui/src/pages/Admin/AllStories/reducer.ts
Labels: frontend

#285 Upload & Edit Stories
  ui/package.json
  ui/src/components/StoryDrawer.tsx
  ui/src/data/cities.json
  ui/src/data/cities.tsx
  ui/src/pages/Admin/Edit/Listbox.tsx
  ui/src/pages/Admin/Edit/UploadStory.tsx
  ui/src/pages/Admin/Edit/UploadStoryWrapper.tsx
  ui/src/pages/Admin/Edit/index.tsx
  ui/src/pages/Admin/Edit/reducer.ts
  ui/src/pages/Admin/Edit/types.tsx
  ui/src/pages/Admin/Upload.tsx
  ui/src/pages/Admin/index.tsx
  ui/src/styles/colors.ts
  ui/yarn.lock
Labels: frontend

#303 feat: upload success screen and positioning fixes
  ui/src/assets/images/success-doodle.svg
  ui/src/pages/Admin/AllStories/index.tsx
  ui/src/pages/Admin/Edit/UploadStory.tsx
  ui/src/pages/Admin/Edit/UploadSuccess.tsx
  ui/src/pages/Admin/index.tsx
  ui/yarn.lock
Labels: design, frontend

#304 Backend File Size Limit
  config/getter.go
  restapi/stories.go
Labels: backend

#294 Jeffrey/all-stories-app-bar
  restapi/stories.go
  ui/src/components/AllStoriesAppBar.tsx
  ui/src/components/StyledButtons.tsx
  ui/src/components/ToastyBoi.tsx
  ui/src/pages/Admin/AllStories/index.tsx
  ui/src/pages/Admin/AllStories/reducer.ts
  ui/src/styles/colors.ts
  ui/src/styles/typography.ts
Labels: frontend

#333 fix: visibility search and bracket space
  ui/src/pages/Admin/AllStories/index.tsx
Labels: frontend

#336 Fix Youtube URL For Preview
  ui/src/components/StoryDrawer.tsx
Labels: frontend

#335 Checkbox Fixes
  ui/src/__tests__/pages/Admin/AllStories.test.ts
  ui/src/pages/Admin/AllStories/index.tsx
  ui/src/pages/Admin/AllStories/reducer.ts
Labels: all-stories, frontend

#337 feat: warning pages on close tab and styling changes
  ui/src/pages/Admin/AllStories/index.tsx
  ui/src/pages/Admin/Edit/UploadStory.tsx
Labels: design, frontend

#339 Flip the bloody arrow
  ui/src/components/StoryDrawer.tsx
Labels: bug, priority: high

#344 Fix login screen graphic
  ui/src/pages/Login.tsx
Labels: bug, priority: medium
